spring:
  application:
    name: blog
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/blog
    username: admin
    password: admin2024
    driver-class-name: com.mysql.cj.jdbc.Driver